#define PROGRAM 1
#define IDENTIFIER 2
#define SEMI_COLON 3
#define VARIABLE 4
#define COMMA 5
#define COLON 6
#define INTEGER 7
#define FLOAT 8
#define LEFT_BRACKET 9
#define RIGHT_BRACKET 10
#define EQUALS 11
#define CTE_STRING 12
#define ADDITION 13
#define SUBSTRACTION 14
#define MULTIPLICATION 15
#define DIVISION 16
#define PRINT 17
#define LEFT_PARENTHESIS 18
#define RIGHT_PARENTHESIS 19
#define IF_CLAUSE 20
#define ELSE_CLAUSE 21
#define CTE_L 22
#define CTE_F 23
#define PERIOD 24